### ISSUE TITLE
Docker Solution for Windows 10 Home Users

### ISSUE THREAD

**Issue by stanley-roache** [PaperHat/centripetal#79]
Currently Windows 10 Home users aren't able to (easily) run Docker/ docker-compose and run the server locally. 

Acceptance Criteria:
Windows 10 Home users can run server locally via docker, instructions are easy to follow on readme

Possible solutions:
- Install Linux (either dual boot or VM)
- Subsidise upgrades to Win PRO
- Figure out a clean process for docker toolbox
- Host server remotely so that not everyone needs to run server locally?

**Comment by walkcoolboy** [comment]
I did it with Ubuntu in VMware Workstation Player (free). Happy to help anyone want to set up the env
